### ISSUE TITLE
Split API into multiple files

### ISSUE THREAD

**Issue by mbuchetics** [onmyway133/AppStoreConnect#1]
Great framework 👍 I would prefer the generated API (`Paths.swift`, `Entities.swift`) to be split up into multiple files. I think CreateAPI should support this.

**Comment by onmyway133** [comment]
@mbuchetics thanks for checking. Splitting would be nice and make it easy to browse.

For me, I'm OK with generated code in 1 file since the are generated code any way. For viewing we have DocC
